### ISSUE TITLE
CellProps value always contains a String

### ISSUE THREAD

**Issue by tanyona** [humbletrader/katechaki#2]
I'm creating a report output class (extending the `AbstractReportOutput` class) and using a `JdbcResultsetTableInput`. However, in the `output(String templateName, T model)` method, for each data row, the `CellProps` value (the model) is always a String object. I would like to output the data differently based on the type of data e.g. the database may return an Integer, Date etc. I see that in the `DataRowsOutputStep.execute()` method, the CellProps.Builder is using the `dataColumn.getFormattedValue(valueForCurrentColumn)`, which always returns a string. Would it be possible to have an option where the actual value is put in the CellProps object, instead of the `toString()` or formatted represenation?

**Comment by humbletrader** [comment]
I understand your need but the solution is too tight to JDBC because other sources may not reveal the type of their data ( for instance CSV input).

**Comment by humbletrader** [comment]
One possible solution is to create a JdbcCellProps when JDBC input is used but I'm not sure I would include this in the library.

**Comment by tanyona** [comment]
That's OK. I'll copy the `DataRowsOutputStep` code and return the data without formatting and use that.
